### ISSUE TITLE
Please add support of recent `eth-account` and `web3`

### ISSUE THREAD

**Issue by amyodov** [HMXOrg/v2-sdk-python#13]
The current `requirements.txt` contains the following lines:

```
eth-account>=0.4.0,<0.6.0
web3>=5.0.0,<6.0.0
```

Current version of `web3` is **6.15.1**; 5.x branch is about [two years old](https://web3py.readthedocs.io/en/stable/releases.html#v5-28-0-2022-02-09) (last release is from February 9, 2022), and doesn't support Python 3.10 and newer.

Current version of `eth-account` is **0.10.0**; 0.5.x branch is [1.5 years old](https://eth-account.readthedocs.io/en/latest/release_notes.html#eth-account-v0-5-9-2022-08-04) (last release is from August 4, 2022), and doesn't support Python 3.9 and newer.

Having the outdated libraries in dependencies makes it problematic to integrate with other libraries, and is potentially security-unsafe.

**Comment by chenciao8** [comment]
Thanks for your suggestion!

In the latest version (currently `v.1.0.1`) we have upgrade `web3` version to latest **6.x.x** along with `eth-account` to **0.10.0** and other packages. You can see full list [here](https://github.com/HMXOrg/v2-sdk-python/blob/main/requirements.txt).

If you have any suggestions, feel free to tell us.
